begin transaction;

drop table if exists users, music, user_playlist;
drop sequence if exists seq_user_id;

create sequence seq_user_id
increment by 1
no maxvalue
no minvalue
cache 1;

create table users (
	user_id int default nextval('seq_user_id'::regclass) not null,
	username varchar (50) not null unique,
	password_hash varchar(200) not null,
	role varchar(50) not null,
	constraint pk_user primary key (user_id)
);

create table music (
	song_id serial not null,
	song varchar (50) not null,
	artist varchar (50) not null,
	album varchar (50) not null,
	user_like boolean,
	genre varchar (50) not null,
	constraint pk_music primary key (song_id)
);

create table user_playlist (
	user_id int,
	song_id int,
	constraint fk_user_playlist_user_id foreign key (user_id) references users(user_id),
	constraint fk_user_playlist_music foreign key (song_id) references music(song_id)
);


insert into users (username, password_hash, role) values ('user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'ROLE USER');
insert into users (username, password_hash, role) values ('admin', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'ROLE_ADMIN');



insert into music (song, artist, album, user_like, genre) 
values	 ('Future People', 'Alabama Shakes', 'Sound & Color', 'Yes', 'Alternative'),
		 ('Rolling in the Deep', 'Adele', '21', 'Yes', 'Pop'),
		 ('You Oughta Know', 'Alanis Morisette', 'Jagged Little Pill', 'Yes', 'Alternative'),
		 ('Fallin', 'Alicia Keys', 'Songs In A Minor', 'Yes', 'R&B/Soul'),
		 ('Breezeblocks', 'alt-j', 'An Awesome Wave', 'Yes', 'Alternative'),
		 ('Wake Up Alone', 'Amy Winehouse', 'Back To Black', 'Yes', 'R&B/Soul'),
		 ('Come Down', 'Anderson .Paak', 'Malibu', 'Yes', 'R&B/Soul'),
		 ('Meet Me At Our Spot', 'THE ANXIETY, WILLOW & Tyler Cole', 'THE ANXIETY', 'Yes', 'Alternative'),
		 ('The Suburbs', 'Arcade Fire', 'The Suburbs', 'Yes', 'Alternative'),
		 ('I Bet You Look Good on the Dancefloor', 'Arctic Monkeys', 'Whatever People Say I Am, Thats What Im Not', 'Yes', 'Alternative'),
		 ('Fake Smile', 'Ariana Grande', 'thank u, next', 'Yes', 'Pop'),
		 ('Everybodys Gotta Live', 'Arthur Lee', 'Vindicator', 'Yes', 'Rock'),
		 ('Because Im Me', 'The Avalanches', 'Wildflower', 'Yes', 'Alternative'),
		 ('Will You Return', 'The Avett Brothers', 'Emotionalism', 'Yes', 'Country'),
		 ('Peach Blossom Boogy', 'Babe Rainbow', 'The Babe Rainbow', 'Yes', 'Alternative'),
		 ('Caught Me Thinking', 'Bahamas', 'Barchords', 'Yes', 'Singer/Songwriter'),
		 ('One Week', 'Barenaked Ladies', 'All Their Greatest Hits', 'Yes', 'Rock'),
		 ('Never, Never Gonna Give Ya Up', 'Barry White', 'Barry Whites Greatest Hits', 'Yes', 'R&B/Soul'),
		 ('Sloop John B', 'The Beach Boys', 'Pet Sounds', 'Yes', 'Rock'),
		 ('In My Life', 'The Beatles', 'Rubber Soul', 'Yes', 'Rock'),
		 ('Hold Up', 'Beyonce', 'Lemonade', 'Yes', 'Pop'),
		 ('Still Fly', 'Big Tymers', 'Hood Rich', 'Yes', 'Hip-Hop/Rap'),
		 ('California Stars', 'Billy Bragg & Wilco', 'Mermaid Avenue', 'Yes', 'Singer/Songwriter'),
		 ('Rise Above', 'Black Flag', 'Damaged', 'Yes', 'Punk'),
		 ('Weight of Love', 'The Black Keys', 'Turn Blue', 'Yes', 'Alternative'),
		 ('Touch the Sky', 'Black Pumas', 'Black Pumas', 'Yes', 'Soul'),
		 ('I Wanna Get Better', 'Bleachers', 'Strange Desire', 'Yes', 'Alternative'),
		 ('Heart of Glass', 'Blondie', 'Parallel Lines', 'Yes', 'Pop'),
		 ('Sutphin Boulevard', 'Blood Orange', 'Coastal Grooves', 'Yes', 'Alternative'),
		 ('Skinny Love', 'Bon Iver', 'For Emma, Forever Ago', 'Yes', 'Alternative'),
		 ('Foreplay/Long Time', 'Boston', 'Boston', 'Yes', 'Rock'),
		 ('Baby', 'Brandy', 'Brandy', 'Yes', 'R&B/Soul'),
		 ('Toxic', 'Britney Spears', 'In the Zone', 'Yes', 'Pop'),
		 ('Stay High', 'Brittany Howard', 'Jamie', 'Yes', 'Alternative'),
		 ('The Mall and Misery', 'Broken Bells', 'Broken Bells', 'Yes', 'Alternative'),
		 ('777', 'Bruno Mars, Anderson .Paak & Silk Sonic', 'An Evening With Silk Sonic', 'Yes', 'R&B/Soul'),
		 ('All the Debts That I Owe', 'Caamp', 'Caamp', 'Yes', 'Contemporary Folk'),
		 ('Jerk It Out', 'Caesers', 'Love for the Streets', 'Yes', 'Pop'),
		 ('Social Cues', 'Cage the Elephant', 'Social Cues', 'Yes', 'Alternative'),
		 ('Slide (feat. Frank Ocean & Migos)', 'Calvin Harris', 'Funk Wav Bounces Vol. 1', 'Yes', 'Dance'),
		 ('I Like It', 'Cardi B', 'Invasion of Privacy', 'Yes', 'Hip-Hop/Rap'),
		 ('Wild World', 'Cat Stevens', 'Tea for the Tillerman', 'Yes', 'Pop'),
		 ('Its All Coming Back to Me Now', 'Celion Dion', 'Falling into You', 'Yes', 'Pop'),
		 ('Juice', 'Chance the Rapper', 'Acid Rap', 'Yes', 'Hip-Hop/Rap'),
		 ('Gold', 'Chet Faker', 'Built on Glass', 'Yes', 'Electronic'),
		 ('BALENCIES', 'CHIKA', 'INDUSTRY GAMES', 'Yes', 'Hip-Hop/Rap'),
		 ('Sober', 'Childish Gambino', 'Kauai', 'Yes', 'Hip-Hop/Rap'),
		 ('Tennessee Whiskey', 'Chris Stapleton', 'Traveller', 'Yes', 'Country'),
		 ('Tubthumping', 'Chumbawamba', 'Tubthumper', 'Yes', 'Rock'),
		 ('One, Two Step (feat. Missy Elliott)', 'Ciara', 'Goodies', 'Yes', 'R&B/Soul'),
		 ('What Would You Do?', 'City High', 'City High', 'Yes', 'R&B/Soul'),
		 ('Animals', 'Coast Modern', 'Coast Modern', 'Yes', 'Rock'),
		 ('Bring It(Snakes Onn a Plane)', 'Cobra Starship', 'While the City Sleeps, We Rule the Streets', 'Yes', 'Alternative'),
		 ('Hang Me up to Dry', 'Cold War Kids', 'Robbers & Cowards', 'Yes', 'Alternative'),
		 ('RNB(feat. Anderson .Paak)', 'Cordae', 'The Lost Boy', 'Yes', 'Hip-Hop/Rap'),
		 ('Zombie', 'The Cranberries', 'No Need To Argue', 'Yes', 'Rock'),
		 ('I Put a Spell On You', 'Creedence Clearwater Revival', 'Creedence Clearwater Revival', 'Yes', 'Rock'),
		 ('The Curse of Curves', 'Cute Is What We Aim For', 'The Same Old Bloodrush With a New Touch', 'Yes', 'Alternative'),
		 ('Oh! You Pretty Things', 'David Bowie', 'Hunky Dory', 'Yes', 'Rock'),
		 ('When My Time Comes', 'Dawes', 'North Hills', 'Yes', 'Alternative'),
		 ('Baltimore Blues No.1', 'Deer Tick', 'War Elephant', 'Yes', 'Alternative'),
		 ('St. Francis', 'Delta Spirit', 'History From Below', 'Yes', 'Alternative'),
		 ('Blame', 'Diamond Rugs', 'Cosmetics', 'Yes', 'Alternative'),
		 ('Jolene', 'Dolly Parton', 'Ultimate Dolly Parton', 'Yes', 'Country'),
		 ('I Feel Love', 'Donna Summer', 'The Dance Collection', 'Yes', 'Pop'),
		 ('Still D.R.E.(feat. Snoop Dogg)', 'Dr.Dre', '2001', 'Yes', 'Pop'),
		 ('Passionfruit', 'Drake', 'More Life', 'Yes', 'Hip-Hop/Rap'),
		 ('Physical', 'Dua Lipa', 'Future Nostalgia', 'Yes', 'Pop'),
		 ('I Cant Tell You Why', 'Eagles', 'The Long Run', 'Yes', 'Rock'),
		 ('Tiny Dancer', 'Elton John', 'Madman Across the Water', 'Yes', 'Pop'),
		 ('Distance', 'Emily King', 'The Switch', 'Yes', 'Soul'),
		 ('Wonderful Tonight', 'Eric Clapton', 'Slowhand', 'Yes', 'Rock'),
		 ('At Last', 'Etta James', 'At Last!', 'Yes', 'Blues'),
		 ('Headfirst Slide into Cooperstown On a Bad Bet', 'Fall Out Boy', 'Follie a Deux', 'Yes', 'Alternative'),
		 ('The Way', 'Fastball', 'All the Pain Money Can Buy', 'Yes', 'Alternative'),
		 ('Moneygrabber', 'Fitz and The Tantrums', 'Pickin Up the Pieces', 'Yes', 'Alternative'),
		 ('Dreams', 'Fleetwood Mac', 'Rumours', 'Yes', 'Rock'),
		 ('Shake It Out', 'Florence + the Machine', 'Ceremonials', 'Yes', 'Alternative'),
		 ('Sit Next to Me', 'Foster the People', 'Sacred Hearts Club', 'Yes', 'Alternative'),
		 ('Lost', 'Frank Ocean', 'channel ORANGE', 'Yes', 'Pop'),
		 ('Chelsea Dagger', 'The Fratellis', 'Costello Music', 'Yes', 'Alternative'),
		 ('Killing Me Softly With His Song', 'Fugees', 'The Score', 'Yes', 'Hip-Hop/Rap'),
		 ('Barlights', 'Fun.', 'Aim and Ignite', 'Yes', 'Alternative'),
		 ('When I Grow Up', 'Garbage', 'Version 2.0', 'Yes', 'Rock'),
		 ('Pearl Cadillac', 'Gary Clar Jr.', 'This Land', 'Yes', 'Rock'),
		 ('San Antone', 'The Ghost of Paul Revere', 'Believe', 'Yes', 'Rock'),
		 ('The Other Side of Paradise', 'Glass Animals', 'How to Be a Human Being', 'Yes', 'Alternative'),
		 ('Superman', 'Goldfinger', 'Hang-ups', 'Yes', 'Rock'),
		 ('I Dont Wanna Be In Love', 'Good Charlotte', 'Good Morning Revival', 'Yes', 'Alternative'),
		 ('Clint Eastwood', 'Gorillaz', 'Gorillaz', 'Yes', 'Alternative'),
		 ('Safari Song', 'Greta Van Fleet', 'From the Fires', 'Yes', 'Rock'),
		 ('Two Weeks', 'Grizzly Bear', 'Veckatimest', 'Yes', 'Alternative'),
		 ('Tongue Tied', 'Grouplove', 'Never Trust a Happy Song', 'Yes', 'Alternative'),
		 ('These Eyes', 'The Guess Who', 'The Greatest of the Guess Who', 'Yes', 'Rock'),
		 ('Clothes Off!', 'Gym Class Heroes', 'As Cruel As School Children', 'Yes', 'Alternative'),
		 ('Little of Your Love', 'HAIM', 'Something To Tell You', 'Yes', 'Alternative'),
		 ('Flagpole Sitta', 'Harvey Danger', 'Where Have All the Merrymakers Gone?', 'Yes', 'Rock'),
		 ('Cat and Dogs', 'The Head and the Heart', 'The Head and the Heart', 'Yes', 'Alternative'),
		 ('Celebrity Skin', 'Hole', 'Celebrity Skin', 'Yes', 'Rock'),
		 ('Hey Rose', 'Houndmouth', 'From the Hills Below the City', 'Yes', 'Singer/Songwriter'),
		 ('Stay', 'Jackson Browne', 'Running on Empty', 'Yes', 'Pop'),
		 ('Fire and Rain', 'James Taylor', 'Sweet Baby James', 'Yes', 'Pop'),
		 ('Revival', 'Jamestown Revival', 'Utah', 'Yes', 'Alternative'),
		 ('Make Me Feel', 'Janelle Monae', 'Dirty Computer', 'Yes', 'R&B/Soul'),
		 ('Me and Bobby McGee', 'Janis Joplin', 'Pearl', 'Yes', 'Rock'),
		 ('White Rabbit', 'Jefferson Airplane', 'Surrealistic Pillow', 'Yes', 'Rock'),
		 ('All Along the Watchtower', 'Jimi Hendrix', 'Voodoo Child: The Jimi Hendrix Collection', 'Yes', 'Rock'),
		 ('Lifes Been Good', 'Joe Walsh', 'But Seriously, Folks...', 'Yes', 'Rock'),
		 ('Take Me Home, Country Roads', 'John Denver', 'Poems, Prayers & Promises', 'Yes', 'Pop'),
		 ('Salisaw Blue', 'John Moreland', 'Big Bad Luv', 'Yes', 'Alternative'),
		 ('Casio', 'Jungle', 'For Ever', 'Yes', 'Electronic'),
		 ('Slow Jamz', 'Twista, Kanye West & Jamie Foxx', 'The College Dropout', 'Yes', 'Pop'),
		 ('Skeleton Song', 'Kate Nash', 'Made of Bricks', 'Yes', 'Pop'),
		 ('Texas Sun', 'Khruangbin & Leon Bridges', 'Texas Sun - EP', 'Yes', 'Indie Rock'),
		 ('Red Eye (feat. HAIM)', 'Kid Cudi', 'Indicud', 'Yes', 'Hip-Hop/Rap'),
		 ('Mr. Brightside', 'The Killers', 'Hot Fuss', 'Yes', 'Rock'),
		 ('Dancing In the Moonlight', 'King Harvest', 'Dancing In the Moonlight', 'Yes', 'Rock'),
		 ('Classic (feat. Powers)', 'The Knocks', '55', 'Yes', 'Electronica'),
		 ('You Go Down Smooth', 'Lake Street Dive', 'Bad Self Portraits', 'Yes', 'Alternative'),
		 ('Doo Wop', 'Lauryn Hill', 'The Miseducation of Lauryn Hill', 'Yes', 'R&B/Soul'),
		 ('I Like Me Better', 'Lauv', 'I Like Me Better - Single', 'Yes', 'Pop'),
		 ('Over the Hills and Far Away', 'Led Zeppelin', 'Houses of the Holy', 'Yes', 'Rock'),
		 ('Smooth Sailin', 'Leon Bridges', 'Coming Home', 'Yes', 'R&B/Soul'),
		 ('When Am I Gonna Lose You', 'Local Natives', 'Violet Street', 'Yes', 'Alternative'),
		 ('Dang! (feat. Anderson .Paak)', 'Mac Miller', 'The Divine Feminine', 'Yes', 'Hip-Hop'),
		 ('Like a Prayer', 'Madonna', 'Like a Prayer', 'Yes', 'Pop'),
		 ('Tadow', 'Masego', 'Lady Lady', 'Yes', 'R&B/Soul'),
		 ('Cold Little Heart', 'Michael Kiwanuka', 'Love & Hate', 'Yes', 'Soul'),
		 ('Portland', 'Middle Brother', 'Middle Brother', 'Yes', 'Alternative'),
		 ('Grace Kelly', 'MIKA', 'Life In Cartoon Motion', 'Yes', 'Pop'),
		 ('Zombie', 'Miley Cyrus', 'Plastic Hearts', 'Yes', 'Rock'),
		 ('The Good Times Are Killing Me', 'Modest Mouse', 'Good News for People Who Love Bad News', 'Yes', 'Rock'),
		 ('Quiet Dog', 'Mos Def', 'The Ecstatic', 'Yes', 'Hip-Hop/Rap'),
		 ('Sheep', 'Mt. Joy', 'Mt. Joy', 'Yes', 'Alternative'),
		 ('Spring Break 1899', 'Murder By Death', 'Red of Tooth and Claw', 'Yes', 'Alternative'),
		 ('Im Not Okay (I Promise)', 'Murder By Death', 'Three Cheers for Sweet Revenge', 'Yes', 'Alternative'),
		 ('I Need Never Get Old', 'Nathaniel Rateliff & The Night Sweats', 'Nathaniel Rateliff & The Night Sweates', 'Yes', 'Rock'),
		 ('About a Girl', 'Nirvana', 'Bleach', 'Yes', 'Alternative'),
		 ('Spiderwebs', 'No Doubt', 'Tragic Kingdom', 'Yes', 'Pop'),
		 ('Gimme the Loot', 'The Notorious B.I.G.', 'Ready to Die', 'Yes', 'Hip-Hop/Rap'),
		 ('Unless Its Kicks', 'Okkervil River', 'The Stage Names', 'Yes', 'Alternative'),
		 ('Wagon Wheel', 'Old Crow Medicine Show', 'O.C.M.S.', 'Yes', 'Singer/Songwriter'),
		 ('Ice Box', 'Omarion', '21', 'Yes', 'R&B/Soul'),
		 ('Roses', 'Outkast', 'Speakerboxxx/The Love Below', 'Yes', 'Hip-Hop/Rap'),
		 ('Just Like a Pill', 'P!nk', 'M!ssunderstood', 'Yes', 'Pop'),
		 ('I Constantly Thank God for Esteban', 'Panic! At the Disco', 'A Fever You Cant Sweat You', 'Yes', 'Alternative'),
		 ('Where Is My Mind?', 'Pixies', 'Surfer Rosa', 'Yes', 'Alternative'),
		 ('I Wanna Be Your Lover', 'Prince', 'Prince', 'Yes', 'R&B/Soul'),
		 ('Bicycle Race', 'Queen', 'Queen: Greatest Hits', 'Yes', 'Rock'),
		 ('No One Knows', 'Queens of the Stone Age', 'Songs for the Deaf', 'Yes', 'Rock'),
		 ('Five On the Five', 'The Raconteurs', 'Consolers of the Lonely', 'Yes', 'Alternative'),
		 ('Goodnight Chicago', 'Rainbow Kitten Surprise', 'RKS', 'Yes', 'Alternative'),
		 ('Cant Hardly Wait', 'The Replacements', 'All for Nothing/Nothing for All', 'Yes', 'Rock'),
		 ('All My Friends', 'The Revivalists', 'Take Good Care', 'Yes', 'Alternative'),
		 ('Shes a Rainbow', 'The Rolling Stones', 'Their Stanic Majesties Request', 'Yes', 'Rock'),
		 ('The Fire', 'The Roots', 'How I Got Over', 'Yes', 'Hip-Hop/Rap'),
		 ('Pansy Waltz', 'Shakey Graves', 'And the War Came', 'Yes', 'Singer/Songwriter'),
		 ('Tainted Love', 'Soft Cell', 'Non-Stop Erotic Cabaret', 'Yes', 'Pop'),
		 ('Stay Flo', 'Solange', 'When I Get Home', 'Yes', 'R&B/Soul'),
		 ('Sugar Dyed', 'St. Paul & The Broken Bones', 'Half the City', 'Yes', 'R&B/Soul'),
		 ('Circadian Rhythms (Dusk)', 'Stop Light Observations', 'Radiation', 'Yes', 'Rock'),
		 ('Juicebox', 'The Strokes', 'First Impressions of Earth', 'Yes', 'Indie Rock'),
		 ('The Less I Know the Better', 'Tame Impala', 'Currents', 'Yes', 'Alternative'),
		 ('Give Me One Reason', 'Tracy Chapman', 'New Beginning', 'Yes', 'Singer/Songwriter'),
		 ('Oxford Comma', 'Vampire Weekend', 'Vampire Weekend', 'Yes', 'Alternative'),
		 ('Pale Blue Eyes', 'The Velvet Underground', 'The Velvet Underground', 'Yes', 'Rock'),
		 ('Ride', 'The Vines', 'Winning Days', 'Yes', 'Adult Alternative'),
		 ('Add It Up', 'Violent Femmes', 'Violent Femmes', 'Yes', 'Alternative'),
		 ('Fell In Love With a Girl', 'The White Stripes', 'White Blood Cells', 'Yes', 'Rock'),
		 ('Colossal', 'Wolfmother', 'Wolfmother', 'Yes', 'Hard Rock'),
		 ('Way Out', 'Yeah Yeah Yeahs', 'Show Your Bones', 'Yes', 'Alternative'),
		 ('Whats Up?', '4 Non Blondes', 'Bigger, Better, Faster, More!', 'Yes', 'Rock')
		 ;
		 


commit;

